### PR TITLE
Closes #386 Fix filtering based on enums

### LINKED ISSUE #386: Fix filtering based on enums
https://github.com/FAForever/faf-java-api/pull/384

### PR DESCRIPTION
**Pull request by bukajsytlos**
Looks like the only broken enum left was faction

### CODE REVIEW

**Review by Brutus5000 — DISMISSED** [review]

File: src/main/java/com/faforever/api/data/domain/Faction.java [hunk 1]
```diff
@@ -26,7 +23,6 @@
     this.string = string;
   }
 
-  @JsonCreator
```
Comment (Brutus5000) [inline src/main/java/com/faforever/api/data/domain/Faction.java:29]: Why removed?

Comment (bukajsytlos) [reply src/main/java/com/faforever/api/data/domain/Faction.java:29]: well we said all string, so we want to send it as string and receive it as string

Comment (Brutus5000) [reply src/main/java/com/faforever/api/data/domain/Faction.java:29]: Ok. Since we don't parse any replays it should be fine.
