### PR TITLE
Closes #448 Analyze/change entity owner permission

### LINKED ISSUE #448: Analyze/change entity owner permission from inline to filter check
```
You remember that pagination exception because of java-side filtering? 
I am wondering if we could refactor the "is entity owner" check into something that can be appended to the SQL
```

### PR DESCRIPTION
**Pull request by bukajsytlos**
Closes #448 Analyze/change entity owner permission from inline to filter check

### CODE REVIEW

File: src/main/java/com/faforever/api/data/checks/IsEntityOwnerFilter.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+  public static class Filter extends FilterExpressionCheck<OwnableEntity> {
+
+    @Override
+    public FilterExpression getFilterExpression(Type<?> entityClass, RequestScope requestScope) {
+      final ElideUser caller = (ElideUser) requestScope.getUser();
+      final int playerId = caller.getFafUserDetails().getId();
+      List<PathElement> pathList = new ArrayList<>();
+      getOwnerPath(entityClass, pathList);
+      Path path = new Path(pathList);
+      return new FilterPredicate(path, Operator.IN, Collections.singletonList(playerId));
```
Comment (Brutus5000) [inline src/main/java/com/faforever/api/data/checks/IsEntityOwnerFilter.java]: List.of(playerId)

File: src/main/java/com/faforever/api/data/checks/IsEntityOwnerFilter.java [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+import java.lang.annotation.RetentionPolicy;
+import java.lang.annotation.Target;
+import java.util.ArrayList;
+import java.util.Arrays;
+import java.util.Collections;
+import java.util.List;
+
+import static com.yahoo.elide.core.type.ClassType.INTEGER_TYPE;
+
+public class IsEntityOwnerFilter {
```
Comment (Brutus5000) [inline src/main/java/com/faforever/api/data/checks/IsEntityOwnerFilter.java:33]: We need a JavaDoc describing when to use this Filter over the normal SecurityCheck

File: src/main/java/com/faforever/api/data/domain/VotingAnswer.java [hunk 3]
```diff
@@ -19,7 +17,6 @@
 @Entity
 @Table(name = "voting_answer")
 @Include(name = VotingAnswer.TYPE_NAME, rootLevel = false)
-@ReadPermission(expression = IsEntityOwner.EXPRESSION)
```
Comment (Brutus5000) [inline src/main/java/com/faforever/api/data/domain/VotingAnswer.java:22]: Why can this be removed?

Comment (bukajsytlos) [reply src/main/java/com/faforever/api/data/domain/VotingAnswer.java:22]: as far as I remember, since this is not root level entity, it is read/accessed via Vote entity which has the read permissions defined, this should be unnecessary.

**Review by Brutus5000 — APPROVED** [review]
