### PR TITLE
Closes #820 Improve handling of failed steam redirect validations

### LINKED ISSUE #820: Improve handling of failed steam redirect validations
On linking to Steam and on password reset via Steam, the user gets redirected to us from Steam with a code. We then ask the Steam API if the code is valid.

If it's not valid (rare case) this unfortunately leads to an internal server error (HTTP 500).
This should cause a bad request instead (HTTP 400) and the log should contain the user id and name (as we have some request in the forum that cannot be correlated to logs).

```
2024-01-08 17:01:15.724  WARN 1 --- [f895bed0-ec2d-4666-b4d6-405e6b907ce1] [io-8010-exec-87] c.f.a.e.GlobalControllerExceptionHandler : Internal server error

java.lang.IllegalArgumentException: Steam redirect could not be validated! Original response:
ns:http://specs.openid.net/auth/2.0
is_valid:false

        at com.faforever.api.user.SteamService.validateSteamRedirect(SteamService.java:82)
        at com.faforever.api.user.UsersController.requestPasswordResetViaSteam(UsersController.java:147)
```

The way to achieve this is to not throw an IllegalArgumentException, but log a useful error and throw an ApiException.of new type STEAM_LOGIN_VALIDATION_FAILED or something.

### PR DESCRIPTION
**Pull request by Ivan-Shaml**
Closes #820 
Note: I have implemented `SteamService#handleInvalidOpenIdRedirect` method, whit the mindset that the validation fails because an attacker tries to exploit the endpoint.

### CODE REVIEW

File: src/main/java/com/faforever/api/user/SteamService.java [hunk 1]
```diff
@@ -73,15 +80,46 @@ void validateSteamRedirect(HttpServletRequest request) {
...
+        LinkedServiceType.STEAM).map(AccountLink::getUser).ifPresentOrElse(u ->
+          log.warn(
+              "Steam redirect could not be validated for user with id: ''{}'' and login: ''{}''. Original OpenID response:\n {}",
+              u.getId(), u.getLogin(), openIdResponseBody),
+        () ->
+          log.warn(
+            "Steam redirect could not be validated! The steam id ''{}'' does not match any account. Original OpenID response:\n {}",
+            StringUtils.deleteWhitespace(steamId).replace("'", ""), // prevent potential log poisoning attack
+            openIdResponseBody)
+      );
```
Comment (Brutus5000) [inline src/main/java/com/faforever/api/user/SteamService.java]: Please adjust formatting so we have on call per line

```
accountLinkRepository.findOneByServiceIdAndServiceType(...)
  .map(...)
  .ifPresentOrElse(...)
```

File: src/main/java/com/faforever/api/user/SteamService.java [hunk 2]
```diff
@@ -73,15 +80,46 @@ void validateSteamRedirect(HttpServletRequest request) {
...
   }
+
+  void handleInvalidOpenIdRedirect(final HttpServletRequest request, final String openIdResponseBody) {
+    boolean containsIdentityParam = request.getParameterMap().containsKey("openid.identity");
+    final String steamId;
+
+    if (containsIdentityParam)
+    {
+       steamId = parseSteamIdFromLoginRedirect(request);
+    } else {
```
Comment (Brutus5000) [inline src/main/java/com/faforever/api/user/SteamService.java]: The `containsIdentityParam` check could be moved into `parseSteamIdFromLoginRedirect` which would then return an Optional.
Then here we could just `.orElseThrow()`

**Review by Brutus5000 — CHANGES_REQUESTED** [review]
Looks good, just 2 minor change requests :D

File: src/main/java/com/faforever/api/user/SteamService.java (hunk 2 above)
Comment (Ivan-Shaml) [reply src/main/java/com/faforever/api/user/SteamService.java]: The `com.faforever.api.user.SteamService#parseSteamIdFromLoginRedirect` method is used directly in the UsersController as well:
 - `com.faforever.api.user.UsersController#requestPasswordResetViaSteam`
 - `com.faforever.api.user.UsersController#linkToSteam`

Wouldn't it be nicer that if the loging + throwing an exception (if identityParam is not contained) get moved inside of the method, because if we make the method to return an Optional, we would need to handle that  the same way on multiple places.

Also with the current implementation of the method if the `openid.identity` parameter is not contained within the request (`request.getParameter("openid.identity")` returns `null`,  we call `.subsring` on `null`, so there is a NPE), definitely the whole method `parseSteamIdFromLoginRedirect` should be revisited anyway ...

**Review by Brutus5000 — APPROVED** [review]
